// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user/user.proto

package user

import (
	common "github.com/pbuser/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x13common/common.proto2\x9a\x01\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"CreateUser\x12\x19.common.CreateUserRequest\x1a\x1a.common.CreateUserResponse\"\x00\x12D\n" +
	"\vGetUserInfo\x12\x1a.common.GetUserInfoRequest\x1a\x17.common.GetUserResponse\"\x002O\n" +
	"\rStreamService\x12>\n" +
	"\tListValue\x12\x15.common.SimpleRequest\x1a\x16.common.StreamResponse\"\x000\x012K\n" +
	"\fStreamClient\x12;\n" +
	"\x06Upload\x12\x15.common.StreamRequest\x1a\x16.common.SimpleResponse\"\x00(\x012F\n" +
	"\x06Stream\x12<\n" +
	"\rConversations\x12\x11.common.StreamReq\x1a\x12.common.StreamResp\"\x00(\x010\x01B!Z\x1fgithub.com/pbuser/genproto/userb\x06proto3"

var file_user_user_proto_goTypes = []any{
	(*common.CreateUserRequest)(nil),  // 0: common.CreateUserRequest
	(*common.GetUserInfoRequest)(nil), // 1: common.GetUserInfoRequest
	(*common.SimpleRequest)(nil),      // 2: common.SimpleRequest
	(*common.StreamRequest)(nil),      // 3: common.StreamRequest
	(*common.StreamReq)(nil),          // 4: common.StreamReq
	(*common.CreateUserResponse)(nil), // 5: common.CreateUserResponse
	(*common.GetUserResponse)(nil),    // 6: common.GetUserResponse
	(*common.StreamResponse)(nil),     // 7: common.StreamResponse
	(*common.SimpleResponse)(nil),     // 8: common.SimpleResponse
	(*common.StreamResp)(nil),         // 9: common.StreamResp
}
var file_user_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.CreateUser:input_type -> common.CreateUserRequest
	1, // 1: user.UserService.GetUserInfo:input_type -> common.GetUserInfoRequest
	2, // 2: user.StreamService.ListValue:input_type -> common.SimpleRequest
	3, // 3: user.StreamClient.Upload:input_type -> common.StreamRequest
	4, // 4: user.Stream.Conversations:input_type -> common.StreamReq
	5, // 5: user.UserService.CreateUser:output_type -> common.CreateUserResponse
	6, // 6: user.UserService.GetUserInfo:output_type -> common.GetUserResponse
	7, // 7: user.StreamService.ListValue:output_type -> common.StreamResponse
	8, // 8: user.StreamClient.Upload:output_type -> common.SimpleResponse
	9, // 9: user.Stream.Conversations:output_type -> common.StreamResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
