// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user/user.proto

package user

import (
	_ "github.com/pbuser/genproto/api"
	common "github.com/pbuser/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x04user\x1a\x13common/common.proto\x1a\x15api/annotations.proto2\xcc\x01\n" +
	"\vUserService\x12_\n" +
	"\n" +
	"CreateUser\x12\x19.common.CreateUserRequest\x1a\x1a.common.CreateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/create\x12\\\n" +
	"\vGetUserInfo\x12\x1a.common.GetUserInfoRequest\x1a\x17.common.GetUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/user/info2O\n" +
	"\rStreamService\x12>\n" +
	"\tListValue\x12\x15.common.SimpleRequest\x1a\x16.common.StreamResponse\"\x000\x012K\n" +
	"\fStreamClient\x12;\n" +
	"\x06Upload\x12\x15.common.StreamRequest\x1a\x16.common.SimpleResponse\"\x00(\x012F\n" +
	"\x06Stream\x12<\n" +
	"\rConversations\x12\x11.common.StreamReq\x1a\x12.common.StreamResp\"\x00(\x010\x012E\n" +
	"\x04Good\x12=\n" +
	"\n" +
	"CreateGood\x12\x15.common.CreateGoodReq\x1a\x16.common.CreateGoodResp\"\x00B!Z\x1fgithub.com/pbuser/genproto/userb\x06proto3"

var file_user_user_proto_goTypes = []any{
	(*common.CreateUserRequest)(nil),  // 0: common.CreateUserRequest
	(*common.GetUserInfoRequest)(nil), // 1: common.GetUserInfoRequest
	(*common.SimpleRequest)(nil),      // 2: common.SimpleRequest
	(*common.StreamRequest)(nil),      // 3: common.StreamRequest
	(*common.StreamReq)(nil),          // 4: common.StreamReq
	(*common.CreateGoodReq)(nil),      // 5: common.CreateGoodReq
	(*common.CreateUserResponse)(nil), // 6: common.CreateUserResponse
	(*common.GetUserResponse)(nil),    // 7: common.GetUserResponse
	(*common.StreamResponse)(nil),     // 8: common.StreamResponse
	(*common.SimpleResponse)(nil),     // 9: common.SimpleResponse
	(*common.StreamResp)(nil),         // 10: common.StreamResp
	(*common.CreateGoodResp)(nil),     // 11: common.CreateGoodResp
}
var file_user_user_proto_depIdxs = []int32{
	0,  // 0: user.UserService.CreateUser:input_type -> common.CreateUserRequest
	1,  // 1: user.UserService.GetUserInfo:input_type -> common.GetUserInfoRequest
	2,  // 2: user.StreamService.ListValue:input_type -> common.SimpleRequest
	3,  // 3: user.StreamClient.Upload:input_type -> common.StreamRequest
	4,  // 4: user.Stream.Conversations:input_type -> common.StreamReq
	5,  // 5: user.Good.CreateGood:input_type -> common.CreateGoodReq
	6,  // 6: user.UserService.CreateUser:output_type -> common.CreateUserResponse
	7,  // 7: user.UserService.GetUserInfo:output_type -> common.GetUserResponse
	8,  // 8: user.StreamService.ListValue:output_type -> common.StreamResponse
	9,  // 9: user.StreamClient.Upload:output_type -> common.SimpleResponse
	10, // 10: user.Stream.Conversations:output_type -> common.StreamResp
	11, // 11: user.Good.CreateGood:output_type -> common.CreateGoodResp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
